//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Infraestructure.Models.MetaData;

    [MetadataType(typeof(ActivoMetadata))]
    public partial class Activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activo()
        {
            this.HistorialDepreciacion = new HashSet<HistorialDepreciacion>();
        }
    
        public int idActivo { get; set; }
        public int numSerie { get; set; }
        public int idTipoActivo { get; set; }
        public string modelo { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public decimal precioColones { get; set; }
        public decimal precioDolares { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaVenceGarantia { get; set; }
        public System.DateTime fechaVenceSeguro { get; set; }
        public string estado { get; set; }
        public byte[] fotoFactura { get; set; }
        public byte[] fotoActivo { get; set; }
        public int idMarca { get; set; }
        public int idAsegurado { get; set; }
        public string cedVendedor { get; set; }
        public int vidaUtil { get; set; }
        public Nullable<decimal> precioActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialDepreciacion> HistorialDepreciacion { get; set; }
        public virtual Asegurado Asegurado { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual TipoActivo TipoActivo { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
