//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Infraestructure.Models.MetaData;

    [MetadataType(typeof(HistorialMetadata))]
    public partial class HistorialDepreciacion
    {
        public int idDepreciacion { get; set; }
        public int idActivo { get; set; }
        public decimal valor { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Activo Activo { get; set; }
    }
}
